"""empty message

Revision ID: 639e792469d7
Revises: f037295f30e7
Create Date: 2026-04-04 11:39:56.750803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639e792469d7'
down_revision = 'f037295f30e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=True))
        batch_op.alter_column('type',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('quiz_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ended_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('question_started_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('session_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('time_spent', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('session_participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('finished_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('total_score', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_participant', schema=None) as batch_op:
        batch_op.drop_column('total_score')
        batch_op.drop_column('finished_at')
        batch_op.drop_column('joined_at')

    with op.batch_alter_table('session_answer', schema=None) as batch_op:
        batch_op.drop_column('answered_at')
        batch_op.drop_column('time_spent')
        batch_op.drop_column('score')

    with op.batch_alter_table('quiz_session', schema=None) as batch_op:
        batch_op.drop_column('question_started_at')
        batch_op.drop_column('ended_at')
        batch_op.drop_column('started_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('points')
        batch_op.drop_column('time_limit')

    # ### end Alembic commands ###
