"""empty message

Revision ID: 976155a56fad
Revises: 0e223accf9dc
Create Date: 2026-01-28 14:05:19.274742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '976155a56fad'
down_revision = '0e223accf9dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_email', type_='unique')

    # ### end Alembic commands ###
