"""empty message

Revision ID: a752c15c0496
Revises: e7292d0187ba
Create Date: 2026-02-18 03:56:09.684233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a752c15c0496'
down_revision = 'e7292d0187ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('runs_count', sa.Integer(), nullable=True))
        batch_op.drop_column('topic')
        batch_op.drop_column('enter_code')
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('enter_code', sa.VARCHAR(length=6), nullable=False))
        batch_op.add_column(sa.Column('topic', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('runs_count')
        batch_op.drop_column('created_at')
        batch_op.drop_column('subject')

    # ### end Alembic commands ###
