"""empty message

Revision ID: d9e5120a6c1a
Revises: 
Create Date: 2025-10-20 21:55:33.410971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9e5120a6c1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('count_questions', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=50), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('enter_code', sa.String(length=6), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enter_code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_order_index'), ['order_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_quiz_id'), ['quiz_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_order', sa.Integer(), nullable=True),
    sa.Column('who_host', sa.Integer(), nullable=False),
    sa.Column('group', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.ForeignKeyConstraint(['who_host'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_session_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_quiz_session_group'), ['group'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_session_quiz_id'), ['quiz_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_session_who_host'), ['who_host'], unique=False)

    op.create_table('requests_to_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('total_result', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['quiz_session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'user_id', 'question_id', name='uq_answer_once')
    )
    with op.batch_alter_table('session_answer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_answer_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_answer_session_id'), ['session_id'], unique=False)

    op.create_table('session_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['quiz_session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'user_id', name='uq_session_user')
    )
    with op.batch_alter_table('session_participant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_participant_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_participant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_participant_session_id'))

    op.drop_table('session_participant')
    with op.batch_alter_table('session_answer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_answer_session_id'))
        batch_op.drop_index(batch_op.f('ix_session_answer_question_id'))

    op.drop_table('session_answer')
    op.drop_table('requests_to_class')
    with op.batch_alter_table('quiz_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_session_who_host'))
        batch_op.drop_index(batch_op.f('ix_quiz_session_quiz_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_session_group'))
        batch_op.drop_index(batch_op.f('ix_quiz_session_code'))

    op.drop_table('quiz_session')
    op.drop_table('users')
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_quiz_id'))
        batch_op.drop_index(batch_op.f('ix_question_order_index'))

    op.drop_table('question')
    op.drop_table('quiz')
    op.drop_table('classes')
    # ### end Alembic commands ###
