"""empty message

Revision ID: e7292d0187ba
Revises: 922a63d668a7
Create Date: 2026-02-16 15:50:38.471737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7292d0187ba'
down_revision = '922a63d668a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('teacher', sa.Integer(), nullable=False),
    sa.Column('specialization', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['teacher'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_column('teacher_name')
        batch_op.drop_column('teacher_initials')
        batch_op.drop_column('specialization')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_email', type_='unique')

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialization', sa.VARCHAR(length=250), nullable=False))
        batch_op.add_column(sa.Column('teacher_initials', sa.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('teacher_name', sa.VARCHAR(length=200), nullable=False))

    op.drop_table('groups')
    # ### end Alembic commands ###
