"""empty message

Revision ID: f037295f30e7
Revises: a752c15c0496
Create Date: 2026-02-18 03:56:38.128590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f037295f30e7'
down_revision = 'a752c15c0496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.String(length=50),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
